#!/usr/bin/env zsh

source env

PG_SCRIPT=${1:-$PG_SCRIPT}

if [[ -z $PG_SCRIPT ]]; then
  echo 'Pass a file as the first parameter' 2>&1
  exit -1
fi

cat "${PG_VARS:-/dev/null}" $PG_SCRIPT | psql -v ON_ERROR_STOP=1
