name:                prosumma
version:             1.9.3.0
github:              "prosumma/prosumma"
license:             MIT 
author:              "Gregory Higley / Prosumma Inc."
maintainer:          "greg@prosumma.com"
copyright:           "2022 Gregory Higley / Prosumma Inc." 

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/prosumma/hs-prosumma#readme>

dependencies:
- aeson
- amazonka >= 2.0 && < 3
- amazonka-core >= 2.0 && < 3
- amazonka-dynamodb >= 2.0 && < 3
- amazonka-kms >= 2.0 && < 3
- amazonka-sns >= 2.0 && < 3
- amazonka-sts >= 2.0 && < 3
- attoparsec
- base >= 4.7 && < 5
- base64-bytestring
- case-insensitive
- composition-prelude
- cryptonite
- data-default
- email-validate
- exceptions
- extra
- formatting
- generic-lens
- hashable
- ip
- lens
- listsafe
- memory
- mtl
- network
- postgresql-simple
- resource-pool
- resourcet
- rio
- servant-auth
- servant-auth-server
- servant-client
- servant-server
- split
- sqlite-simple
- string-conversions
- tagged
- template-haskell
- text
- uuid
- vector
- wai
- warp

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wno-name-shadowing
- -Wno-orphans
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- DataKinds
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- TypeApplications
- TypeSynonymInstances

library:
  source-dirs: src

executables:
  prosumma-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prosumma

tests:
  library-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - async
    - hspec
    - hspec-expectations
    - prosumma
    - random

