name:                prosumma
version:             0.1.0.0
github:              "prosumma/prosumma"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/prosumma#readme>

dependencies:
- aeson
- amazonka >= 2.0 && < 3
- amazonka-core >= 2.0 && < 3
- amazonka-dynamodb >= 2.0 && < 3
- amazonka-kms >= 2.0 && < 3
- amazonka-s3 >= 2.0 && < 3
- amazonka-sts >= 2.0 && < 3
- base >= 4.7 && < 5
- base64-bytestring
- bytestring
- composition-prelude
- data-default
- exceptions
- extra
- formatting
- generic-lens
- lens
- listsafe
- monad-control
- mtl
- postgresql-simple
- regex-tdfa
- resource-pool
- rio
- servant-auth
- servant-auth-server
- servant-client
- servant-server
- string-conversions
- template-haskell
- text
- text-format == 0.3.2.1
- triplesec
- unliftio
- uuid
- wai
- warp

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wno-name-shadowing
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- ScopedTypeVariables

library:
  source-dirs: src

executables:
  auth:
    main:                Main.hs
    source-dirs:         apps/auth/server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prosumma

tests:
  library-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - async
    - hspec
    - hspec-expectations
    - prosumma
    - random
  auth-test:
    main:                Spec.hs
    source-dirs:         apps/auth/test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hspec-expectations
    - http-client
    - http-types
    - HUnit 
    - prosumma
    - servant-client
