name:                prosumma
version:             0.1.0.0
github:              "prosumma/prosumma"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/prosumma#readme>

dependencies:
- amazonka >= 2.0 && < 3
- amazonka-core >= 2.0 && < 3
- amazonka-sts >= 2.0 && < 3
- base >= 4.7 && < 5
- exceptions
- mtl
- rio

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wno-name-shadowing
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - ScopedTypeVariables

library:
  source-dirs: src

executables:
  prosumma-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prosumma

tests:
  prosumma-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hspec-expectations
    - prosumma
